# Generated by Django 4.1.2 on 2022-10-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("firstname", models.CharField(max_length=254)),
                ("lastname", models.CharField(max_length=254)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
    ]
